---
# tasks file for rhads-setup
- name: Install pip for Python 3.11
  command: dnf install python3.11-pip -y

- name: Install openshift and kubernetes Python packages
  command: /usr/libexec/platform-python -m pip install openshift kubernetes

- name: Install kubernetes and openshift for python3.11 user
  command: python3.11 -m pip install --user kubernetes openshift jmespath

- name: Install community.kubernetes collection
  ansible.builtin.command: ansible-galaxy collection install community.kubernetes

- name: Save user1 data
  agnosticd_user_info:
    user: user1
    data:
      openshift_cluster_ingress_domain: "{{ openshift_cluster_ingress_domain }}"
      openshift_console_url: "{{ openshift_console_url }}"
      openshift_user_password: "{{ jenkins_password }}"
